using System.Text.Json;
using System.Text.Json.Serialization;

namespace BridgeTester1.NewStructure2
{
    public static class TestRunner
    {
        private static readonly JsonSerializerOptions MinifyOptions = new()
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.Never,
            Converters = { new JsonStringEnumConverter() }
        };

        public static void Run()
        {
            RunSuite("SELECT", GenerateSelectTests(), sql => new SqlParser(sql).ParseSelect());
            RunSuite("WHERE", GenerateWhereTests(), sql => new SqlParser(sql).ParseWhere());
            RunSuite("ORDER BY", GenerateOrderByTests(), sql => new SqlParser(sql).ParseOrderBy());
        }

        private static (string sql, string expected)[] GenerateSelectTests()
        {
            return new (string, string)[]
            {
                // Level 1: Basics
                ("Par", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Alias\":null}]}"),
                ("MktValue, Par", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"MktValue\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Alias\":null}]}"),
                ("AssetType AS Type", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"Alias\":\"Type\"}]}"),
                ("mKtVaLuE AS market_value", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"mKtVaLuE\"},\"Alias\":\"market_value\"}]}"),
                ("100 AS Const", "{\"Projections\":[{\"Expression\":{\"$type\":\"literal\",\"Value\":100},\"Alias\":\"Const\"}]}"),
                
                // Level 2: Binary Math
                ("Par + GL", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"GL\"}},\"Alias\":null}]}"),
                ("Par - GL AS Net", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"GL\"}},\"Alias\":\"Net\"}]}"),
                ("Price * Qty AS Value", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"Qty\"}},\"Alias\":\"Value\"}]}"),
                ("Price / 100 AS Pct", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Div\",\"Right\":{\"$type\":\"literal\",\"Value\":100}},\"Alias\":\"Pct\"}]}"),
                ("A + B + C AS Total", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Alias\":\"Total\"}]}"),
                
                // Level 3: Brackets & Precedence
                ("(A + B) * C", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Alias\":null}]}"),
                ("A + B * C", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}}},\"Alias\":null}]}"),
                ("A + (B - C) * D AS MixedOrder", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}},\"Alias\":\"MixedOrder\"}]}"),
                ("Price * 1.10 AS MarkUp", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":1.10}},\"Alias\":\"MarkUp\"}]}"),
                ("100 * (A + B) / 10", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"literal\",\"Value\":100},\"Op\":\"Mul\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}}},\"Op\":\"Div\",\"Right\":{\"$type\":\"literal\",\"Value\":10}},\"Alias\":null}]}"),
                
                // Level 4: Aggregates
                ("SUM(Par) AS S", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"Alias\":\"S\"}]}"),
                ("MAX(Price), MIN(Price)", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Max\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Price\"}},\"Alias\":null},{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Min\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Price\"}},\"Alias\":null}]}"),
                ("AVG(Qty) AS Mean", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Avg\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Qty\"}},\"Alias\":\"Mean\"}]}"),
                ("COUNT(ID) AS Vol", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Count\",\"Argument\":{\"$type\":\"field\",\"Name\":\"ID\"}},\"Alias\":\"Vol\"}]}"),
                ("SUM(A + B) AS TotalSum", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}}},\"Alias\":\"TotalSum\"}]}"),
                
                // Level 5: Agg Math
                ("SUM(Par) / COUNT(ID) AS AvgPar", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"Op\":\"Div\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Count\",\"Argument\":{\"$type\":\"field\",\"Name\":\"ID\"}}},\"Alias\":\"AvgPar\"}]}"),
                ("SUM(P) + SUM(G) - SUM(L)", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"P\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"G\"}}},\"Op\":\"Sub\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"L\"}}},\"Alias\":null}]}"),
                ("MAX(Price) - MIN(Price) AS Spread", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Max\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Price\"}},\"Op\":\"Sub\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Min\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Price\"}}},\"Alias\":\"Spread\"}]}"),
                ("SUM(Par) * 0.01 AS Fee", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":0.01}},\"Alias\":\"Fee\"}]}"),
                ("COUNT(ID) + 1 AS NextId", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Count\",\"Argument\":{\"$type\":\"field\",\"Name\":\"ID\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Alias\":\"NextId\"}]}"),
                
                // Level 6: Conditionals
                ("IF A > 10 THEN 'H' ELSE 'L'", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":10}},\"Then\":{\"$type\":\"literal\",\"Value\":\"H\"},\"Else\":{\"$type\":\"literal\",\"Value\":\"L\"}},\"Alias\":null}]}"),
                ("IF A = B THEN 1 ELSE 0 AS Match", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Then\":{\"$type\":\"literal\",\"Value\":1},\"Else\":{\"$type\":\"literal\",\"Value\":0}},\"Alias\":\"Match\"}]}"),
                ("IF P > 0 THEN P ELSE 0 AS PosOnly", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"P\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Then\":{\"$type\":\"field\",\"Name\":\"P\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}},\"Alias\":\"PosOnly\"}]}"),
                ("IF Status = 'Closed' THEN 0 ELSE Price AS ActivePrice", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Status\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Closed\"}},\"Then\":{\"$type\":\"literal\",\"Value\":0},\"Else\":{\"$type\":\"field\",\"Name\":\"Price\"}},\"Alias\":\"ActivePrice\"}]}"),
                ("IF (A + B) > 100 THEN 1 ELSE 0", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":100}},\"Then\":{\"$type\":\"literal\",\"Value\":1},\"Else\":{\"$type\":\"literal\",\"Value\":0}},\"Alias\":null}]}"),
                
                // Level 7: Nested Conditionals
                ("IF A > 10 THEN 'H' ELSE IF A > 5 THEN 'M' ELSE 'L' AS Gr", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":10}},\"Then\":{\"$type\":\"literal\",\"Value\":\"H\"},\"Else\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":5}},\"Then\":{\"$type\":\"literal\",\"Value\":\"M\"},\"Else\":{\"$type\":\"literal\",\"Value\":\"L\"}}},\"Alias\":\"Gr\"}]}"),
                ("SUM(IF R = 'AAA' THEN P ELSE 0) AS AaaAmt", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"R\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"AAA\"}},\"Then\":{\"$type\":\"field\",\"Name\":\"P\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}}},\"Alias\":\"AaaAmt\"}]}"),
                ("MAX(IF A = 1 THEN B ELSE 0) AS Result", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Max\",\"Argument\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"field\",\"Name\":\"B\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}}},\"Alias\":\"Result\"}]}"),
                ("IF SUM(P) > 1000 THEN 'Big' ELSE 'Small' AS Size", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"P\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":1000}},\"Then\":{\"$type\":\"literal\",\"Value\":\"Big\"},\"Else\":{\"$type\":\"literal\",\"Value\":\"Small\"}},\"Alias\":\"Size\"}]}"),
                ("IF A=1 THEN 'Y' ELSE 'N' AS Short", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"literal\",\"Value\":\"Y\"},\"Else\":{\"$type\":\"literal\",\"Value\":\"N\"}},\"Alias\":\"Short\"}]}"),
                
                // Level 8: Deep Recursion
                ("1 + 2 + 3 + 4 + 5 AS Seq", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"literal\",\"Value\":1},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":3}},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":4}},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":5}},\"Alias\":\"Seq\"}]}"),
                ("(((A+B)*C)/D)+E AS Deep", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"E\"}},\"Alias\":\"Deep\"}]}"),
                ("A * B / C * D AS MulDivChain", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}},\"Alias\":\"MulDivChain\"}]}"),
                ("A + B * C + D AS Prec", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}},\"Alias\":\"Prec\"}]}"),
                ("123.45 AS ConstantVal", "{\"Projections\":[{\"Expression\":{\"$type\":\"literal\",\"Value\":123.45},\"Alias\":\"ConstantVal\"}]}"),

                // Level 9: Mixed Mode
                ("Field1, Field2, Field3, Field4, Field5", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field1\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field2\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field3\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field4\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field5\"},\"Alias\":null}]}"),
                ("SUM(P) / COUNT(ID) AS Avg", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"P\"}},\"Op\":\"Div\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Count\",\"Argument\":{\"$type\":\"field\",\"Name\":\"ID\"}}},\"Alias\":\"Avg\"}]}"),
                ("IF A > B THEN A ELSE B AS Big", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Then\":{\"$type\":\"field\",\"Name\":\"A\"},\"Else\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Alias\":\"Big\"}]}"),
                ("AssetType AS T, Rating AS R, SUM(Par) AS S", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"Alias\":\"T\"},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Alias\":\"R\"},{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"Alias\":\"S\"}]}"),
                ("MAX(IF S = 'Active' THEN Price ELSE 0) AS PeakActive", "{\"Projections\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Max\",\"Argument\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"S\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Active\"}},\"Then\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}}},\"Alias\":\"PeakActive\"}]}"),
                
                // Level 10: Logic Combos
                ("IF A=1 THEN (B+C) ELSE (B-C) AS BranchMath", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}}},\"Alias\":\"BranchMath\"}]}"),
                ("SUM(IF A>0 THEN A ELSE 0) + SUM(IF B>0 THEN B ELSE 0) AS DoubleSum", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Then\":{\"$type\":\"field\",\"Name\":\"A\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}}},\"Op\":\"Add\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Then\":{\"$type\":\"field\",\"Name\":\"B\"},\"Else\":{\"$type\":\"literal\",\"Value\":0}}}},\"Alias\":\"DoubleSum\"}]}"),
                ("IF X=1 THEN A ELSE IF X=2 THEN B ELSE IF X=3 THEN C ELSE D AS Quad", "{\"Projections\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"field\",\"Name\":\"A\"},\"Else\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Then\":{\"$type\":\"field\",\"Name\":\"B\"},\"Else\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":3}},\"Then\":{\"$type\":\"field\",\"Name\":\"C\"},\"Else\":{\"$type\":\"field\",\"Name\":\"D\"}}}},\"Alias\":\"Quad\"}]}"),
                ("A, B, C, D, E", "{\"Projections\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"B\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"C\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"D\"},\"Alias\":null},{\"Expression\":{\"$type\":\"field\",\"Name\":\"E\"},\"Alias\":null}]}"),
                ("1 + (2 * 3) / 4 AS MathConst", "{\"Projections\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"literal\",\"Value\":1},\"Op\":\"Add\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"literal\",\"Value\":2},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":3}},\"Op\":\"Div\",\"Right\":{\"$type\":\"literal\",\"Value\":4}}},\"Alias\":\"MathConst\"}]}")
            };
        }

        private static (string sql, string expected)[] GenerateWhereTests()
        {
            return new (string, string)[]
            {
                ("A = 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}"),
                ("AssetType = 'Equity'", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Equity\"}}}"),
                ("AssetType <> 'Cash'", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"Op\":\"NotEq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Cash\"}}}"),
                ("Par > 1000", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":1000}}}"),
                ("Par < 500", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Lt\",\"Right\":{\"$type\":\"literal\",\"Value\":500}}}"),
                ("A = 1 AND B = 2", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}}}}"),
                ("A = 1 OR B = 2", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}}}}"),
                ("A = 1 OR A = 2 OR A = 3", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":3}}}}"),
                ("A = 1 AND B = 2 AND C = 3", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":3}}}}"),
                ("A = 1 OR B = 2 AND C = 3", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":3}}}}}"),
                ("(A = 1 OR B = 1) AND C = 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("A = 1 AND (B = 1 OR C = 1)", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}}"),
                ("((A = 1 AND B = 1) OR (C = 1 AND D = 1))", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"D\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}}"),
                ("A > 10 AND B > 20 AND C > 30", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":10}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":20}}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":30}}}}"),
                ("X = 1 OR Y = 1 OR Z = 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Y\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Z\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("(A + B) > 100", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":100}}}"),
                ("Price * Qty = Value", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"Qty\"}},\"Op\":\"Eq\",\"Right\":{\"$type\":\"field\",\"Name\":\"Value\"}}}"),
                ("A + B > C + D", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}}}"),
                ("Par / 100 > 0.5", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Div\",\"Right\":{\"$type\":\"literal\",\"Value\":100}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0.5}}}"),
                ("(A - B) < (C - D)", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Lt\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}}}"),
                ("A BETWEEN 1 AND 10", "{\"Expression\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Lower\":{\"$type\":\"literal\",\"Value\":1},\"Upper\":{\"$type\":\"literal\",\"Value\":10}}}"),
                ("Price BETWEEN 100 AND 500", "{\"Expression\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Lower\":{\"$type\":\"literal\",\"Value\":100},\"Upper\":{\"$type\":\"literal\",\"Value\":500}}}"),
                ("A BETWEEN (B - 1) AND (B + 1)", "{\"Expression\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Lower\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Upper\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("GL BETWEEN (Par * -1) AND Par", "{\"Expression\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"GL\"},\"Lower\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"unary\",\"Op\":\"Sub\",\"Operand\":{\"$type\":\"literal\",\"Value\":1}}},\"Upper\":{\"$type\":\"field\",\"Name\":\"Par\"}}}"),
                ("A BETWEEN 1 AND 10 AND B = 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Lower\":{\"$type\":\"literal\",\"Value\":1},\"Upper\":{\"$type\":\"literal\",\"Value\":10}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("-A = -1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"unary\",\"Op\":\"Sub\",\"Operand\":{\"$type\":\"field\",\"Name\":\"A\"}},\"Op\":\"Eq\",\"Right\":{\"$type\":\"unary\",\"Op\":\"Sub\",\"Operand\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("A <> B AND C <> D", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"NotEq\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"NotEq\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}}}"),
                ("A >= 100 AND A <= 200", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gte\",\"Right\":{\"$type\":\"literal\",\"Value\":100}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Lte\",\"Right\":{\"$type\":\"literal\",\"Value\":200}}}}"),
                (" ( ( A = 1 ) ) ", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}"),
                ("A = 'X' AND B = 'Y'", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"X\"}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Y\"}}}}"),
                ("IF A = 1 THEN B = 1 ELSE B = 0", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}}"),
                ("IF Flag = 1 THEN A > 0 ELSE A <= 0", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Flag\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Lte\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}}"),
                ("IF Status = 'Active' THEN Price > 0 ELSE Price = 0", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Status\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Active\"}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}}"),
                ("IF A = 1 THEN B = 1 ELSE IF A = 2 THEN B = 2 ELSE B = 0", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Else\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}}}"),
                ("X = 10 OR X = 20 OR X = 30 OR X = 40", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":10}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":20}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":30}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":40}}}}"),
                ("A=1 AND (B=2 OR C=3) AND D=4", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":2}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":3}}}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"D\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":4}}}}"),
                ("Rating = 'AAA' AND Par > 1000", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"AAA\"}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":1000}}}}"),
                ("Rating = 'AAA' OR Rating = 'AA' OR Rating = 'A'", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"AAA\"}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"AA\"}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"A\"}}}}"),
                ("A + B + C > X + Y + Z", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"Y\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"Z\"}}}}"),
                ("Price * 1.1 > Target", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":1.1}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"field\",\"Name\":\"Target\"}}}"),
                ("A = 1 AND B = 1 OR C = 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("X <> 0 AND (Y / X) > 1", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"X\"},\"Op\":\"NotEq\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Y\"},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"X\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}"),
                ("A = 'A' OR B = 'B' AND C = 'C' OR D = 'D'", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"A\"}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"B\"}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"C\"}}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"D\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"D\"}}}}"),
                ("Par > 0 AND (GL / Par) < -0.5", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"GL\"},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"Op\":\"Lt\",\"Right\":{\"$type\":\"unary\",\"Op\":\"Sub\",\"Operand\":{\"$type\":\"literal\",\"Value\":0.5}}}}}"),
                ("IF A = B THEN (C + D) > 0 ELSE (E - F) < 0", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"E\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"F\"}},\"Op\":\"Lt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}}"),
                ("A BETWEEN 100 AND 200 OR A BETWEEN 300 AND 400", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Lower\":{\"$type\":\"literal\",\"Value\":100},\"Upper\":{\"$type\":\"literal\",\"Value\":200}},\"Op\":\"Or\",\"Right\":{\"$type\":\"between\",\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"Lower\":{\"$type\":\"literal\",\"Value\":300},\"Upper\":{\"$type\":\"literal\",\"Value\":400}}}}"),
                ("(A * B) + (C * D) <> (E / F)", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}},\"Op\":\"NotEq\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"E\"},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"F\"}}}}"),
                ("IF Rating = 'AAA' THEN Par > 1000 ELSE Par > 500 AND Status = 'Active'", "{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Rating\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"AAA\"}},\"Then\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":1000}},\"Else\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":500}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Status\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":\"Active\"}}}}}"),
                ("( ( ( A = 1 ) AND ( B = 1 ) ) OR ( ( C = 1 ) AND ( D = 1 ) ) )", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"B\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}},\"Op\":\"Or\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Op\":\"And\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"D\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}}}}}")
                ,("((A + B) * (C - D)) / E > 0", "{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"C\"},\"Op\":\"Sub\",\"Right\":{\"$type\":\"field\",\"Name\":\"D\"}}},\"Op\":\"Div\",\"Right\":{\"$type\":\"field\",\"Name\":\"E\"}},\"Op\":\"Gt\",\"Right\":{\"$type\":\"literal\",\"Value\":0}}}")
            };
        }

        private static (string sql, string expected)[] GenerateOrderByTests()
        {
            return new (string, string)[] {
                // Levels 1-10: IDs and Directives
                ("MktValue", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"MktValue\"},\"IsAscending\":true}]}"),
                ("Par ASC", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"Par\"},\"IsAscending\":true}]}"),
                ("Par DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"Par\"},\"IsAscending\":false}]}"),
                ("AssetType ASC, Par DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"IsAscending\":true},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Par\"},\"IsAscending\":false}]}"),
                ("Field1, Field2, Field3", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field1\"},\"IsAscending\":true},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field2\"},\"IsAscending\":true},{\"Expression\":{\"$type\":\"field\",\"Name\":\"Field3\"},\"IsAscending\":true}]}"),
                ("A DESC, B DESC, C DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"A\"},\"IsAscending\":false},{\"Expression\":{\"$type\":\"field\",\"Name\":\"B\"},\"IsAscending\":false},{\"Expression\":{\"$type\":\"field\",\"Name\":\"C\"},\"IsAscending\":false}]}"),
                
                // Levels 11-20: Expressions in Order By
                ("Par + GL", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"GL\"}},\"IsAscending\":true}]}"),
                ("Par + GL DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Par\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"GL\"}},\"IsAscending\":false}]}"),
                ("SUM(Par)", "{\"Terms\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"IsAscending\":true}]}"),
                ("SUM(Par) DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"Par\"}},\"IsAscending\":false}]}"),
                ("IF A = 1 THEN B ELSE C", "{\"Terms\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"field\",\"Name\":\"B\"},\"Else\":{\"$type\":\"field\",\"Name\":\"C\"}},\"IsAscending\":true}]}"),
                ("IF A = 1 THEN B ELSE C DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"conditional\",\"Condition\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Eq\",\"Right\":{\"$type\":\"literal\",\"Value\":1}},\"Then\":{\"$type\":\"field\",\"Name\":\"B\"},\"Else\":{\"$type\":\"field\",\"Name\":\"C\"}},\"IsAscending\":false}]}"),
                ("Price * 1.10", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":1.10}},\"IsAscending\":true}]}"),
                ("Price * 1.10 DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"literal\",\"Value\":1.10}},\"IsAscending\":false}]}"),
                ("A + B + C", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"IsAscending\":true}]}"),
                ("A + B + C DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"IsAscending\":false}]}"),
                ("AssetType, Price * Qty", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"IsAscending\":true},{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"Qty\"}},\"IsAscending\":true}]}"),
                ("AssetType ASC, Price * Qty DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"field\",\"Name\":\"AssetType\"},\"IsAscending\":true},{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"Price\"},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"Qty\"}},\"IsAscending\":false}]}"),
                ("(A + B) * C", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"field\",\"Name\":\"A\"},\"Op\":\"Add\",\"Right\":{\"$type\":\"field\",\"Name\":\"B\"}},\"Op\":\"Mul\",\"Right\":{\"$type\":\"field\",\"Name\":\"C\"}},\"IsAscending\":true}]}"),
                ("SUM(P) / COUNT(ID) DESC", "{\"Terms\":[{\"Expression\":{\"$type\":\"binary\",\"Left\":{\"$type\":\"aggregate\",\"Func\":\"Sum\",\"Argument\":{\"$type\":\"field\",\"Name\":\"P\"}},\"Op\":\"Div\",\"Right\":{\"$type\":\"aggregate\",\"Func\":\"Count\",\"Argument\":{\"$type\":\"field\",\"Name\":\"ID\"}}},\"IsAscending\":false}]}")
            };
        }

        private static void RunSuite(string label, (string sql, string expected)[] suite, Func<string, object> parseFunc)
        {
            Console.WriteLine($"\n--- {label} SUITE ---");
            int passedCount = 0;

            foreach (var test in suite)
            {
                try
                {
                    var actualObj = parseFunc(test.sql);
                    string actualJson = JsonSerializer.Serialize(actualObj, MinifyOptions);
                    bool pass = string.Equals(actualJson, test.expected);

                    if (pass)
                    {
                        Console.ForegroundColor = ConsoleColor.Green;
                        Console.WriteLine($"[PASS] SQL: {test.sql}");
                        passedCount++;
                    }
                    else
                    {
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine($"[FAIL] SQL: {test.sql}");
                        Console.WriteLine($"   Expected: {test.expected}");
                        Console.WriteLine($"   Actual:   {actualJson}");
                    }
                }
                catch (Exception ex)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"[ERROR] SQL: {test.sql} - {ex.Message}");
                }
                finally { Console.ResetColor(); }
            }
            Console.WriteLine($"\n{label} Summary: {passedCount}/{suite.Length} Passed.");
        }
    }




}
